<script lang="ts" setup>
import { RouterLink } from 'vue-router'
import EmailLink from '@/components/email-link/EmailLink.vue'
</script>

<template>
  <div class="document">
    <div class="title">PRIVACY POLICY</div>
    <div class="subtitle">
      <p>AI Boy Friend (HK) Limited</p>
      <p>506A, Jubilee Square, Shatin, NT, Hong Kong</p>
    </div>
    <div class="subtitle">
      <p>email:<EmailLink /></p>
      <p>Last updated:4 December, 2023</p>
    </div>

    <section>
      This policy applies to personal information held about our customers, our suppliers and
      prospective suppliers, people who visit our websites, and anyone else whose personal
      information we hold.
    </section>

    <section>
      In this policy, “we,” “us,” and “our” means AI Boy Friend (HK) Limited,506A, Jubilee Square,
      Shatin, NT, Hong Kong.This policy deals with where we are acting as a 'data controller' under
      the data protection legislation: which essentially means where we are responsible for deciding
      what personal information we collect and how we use it. We also often operate as a 'data
      processor', meaning that we are processing personal information on behalf of another entity
      (for example a publisher of one of our games).When we refer to "personal information", we mean
      “personal” relating to you personally or from which you can be identified. Some of the
      information mentioned in this policy is not "personal information" as is meant under data
      protection legislation, but we may refer to it to help you understand what we do.
    </section>

    <section>
      We are committed to protecting and respecting the personal information of everyone we deal
      with - that is important to us and we know it is important to you.If you are a California
      resident, please see
      <RouterLink to="/additional">Additional Information For California Residents</RouterLink>
      For California Residentsfor additional disclosures.
    </section>

    <section>
      In this policy you will find information about what types of personal information we hold
      about you, how and why we collect it, how we use it, and how we keep it secure. You will also
      find the information about your rights and how you may exercise them.
    </section>

    <section>
      Please read this policy carefully and if you need to contact us about anything that is in
      here, or for anything else related to your personal information, you can reach us by email at
      <EmailLink />
      or by post at the above address.
    </section>

    <section>
      <p>You'll find in this policy information about the following:</p>
      <p><em>1.What information do we collect about you?</em></p>
      <p>
        What information we hold will depend on our relationship with you. Typically, this may
        include the following:
      </p>

      <p>Customers/players</p>

      <p>
        We will collect some information about you to enable you to play our games, to improve or
        optimise your gaming experience, to provide customer services, to improve the services we
        provide and for marketing (see below for more details). This includes:
      </p>

      <ul>
        <li>
          Your contact information such as name and (if you choose to provide them) your phone
          number and email address;
        </li>
        <li>Your player username and password;</li>
        <li>
          Your game profile – including your profile picture and any information needed for the game
          to function, such as an inventory of in-game items;
        </li>
        <li>
          Other data you choose to give us such as data to identify a lost or lapsed account such as
          the answer to a special question we may ask you in order to permit you to unlock or
          recover a lost or lapsed account;
        </li>
        <li>
          Your game user account or role ID(s) – Our specific ID(s) generated by our game server for
          you;
        </li>
        <li>
          Analytics ID – a randomly generated anonymous identifier used to distinguish activity from
          one game account versus another in our analytics data;
        </li>
        <li>
          Third party account ID – for example your account with Facebook, Xbox, Game Center, VK,
          WeChat, Google, Steam or PSN which you may use to sign into your game account, leverage
          your social graph, or integrate with third party features (such as achievements);
        </li>
        <li>
          Usage data including information about how you use our website, products and services and
          your game progress;
        </li>
        <li>
          Your internet protocol (IP) address and mobile device identifiers (such as for example
          your device ID, advertising ID, MAC address, IMEI);
        </li>
        <li>Data to fight fraud (such as refund abuse in games or click fraud in advertising);</li>
        <li>
          Data about your device, such as device name and operating system, browser type and
          language;
        </li>
        <li>
          Marketing and communications data including your preferences in receiving marketing from
          us and our third parties and your communication preferences and it is at your full own
          discretion and control to adjust the settings on your device to turn off the function.
        </li>
      </ul>
    </section>

    <section>
      <p>Our suppliers</p>
      <p>
        We will collect contact information so that we can manage our relationship with you, and,
        where applicable we may collect bank account details (to enable payment for services). When
        you provide services to us we may collect other information from you which is relevant to
        the provision of those services.
      </p>
      <p>Job applicants</p>
      <p>
        If you apply for a job with us, or send us your CV, we will collect information relevant to
        the position that you apply for and will keep a copy of your CV for as long as is necessary
        in order to assess your suitability for a position with us. This will be explained in more
        detail at the time you make any application.
      </p>
    </section>

    <section>
      <p><em>2.How we collect information about you</em></p>
      <p>
        We will collect this information in a variety of ways depending on how we interact with you.
      </p>
      <p>Direct interactions</p>
      <p>
        You may give us your identity, contact or other information by filling in online forms or by
        corresponding with us by post, phone, in-game, email or otherwise. This includes personal
        data you provide when you:
      </p>
      <ul>
        <li>Use our products or services;</li>
        <li>Create a game account in one of our games or on our website, if any;</li>
        <li>Interact with our Customer Services or our Privacy Office;</li>
        <li>Subscribe to our mailing lists;</li>
        <li>Enter a competition, promotion or survey;</li>
        <li>Give us feedback;</li>
        <li>Provide services to us.</li>
      </ul>
      <p>Third parties</p>
      <ul>
        <li>
          We may receive personal data from a third party. if you link it with the Service or make
          it available to us via your privacy settings. This may include your third party account
          ID, game profile and user ID – for example from your account with Facebook, Game Center,
          VK, WeChat, Google, Xbox, Steam or PSN which you may use to sign into your game account,
          leverage your social graph, or integrate with third party features (such as achievements).
        </li>
        <li>Technical data from advertising networks and</li>
        <li>search information providers.</li>
        <li>References and other information if you apply for a position with us.</li>
      </ul>
    </section>

    <section>
      <p><em>3.How we use your information</em></p>
      <p>We use different information in different ways:</p>
      <ul>
        <li>
          To send you communications related to our services and games, answer your enquiries or
          deal with your complaints;
        </li>
        <li>Providing and managing our services including our games;</li>
        <li>Allowing you to participate in our website features;</li>
        <li>
          Verifying and confirming payments (where relevant interacting with third party payment
          providers);
        </li>
        <li>Account verification and clearance;</li>
        <li>
          Direct marketing letting you know about products and services that may be of particular
          interest to you;
        </li>
        <li>Administering surveys and opinion polls;</li>
        <li>Managing competitions and/or promotions and your registration for the same;</li>
        <li>
          Technical and usage information/analytics to help us develop games that our customers want
          to play and to improve them and to detect cheating and activities that ruin the experience
          of players using our games, security risks, fraud and other unlawful activity;
        </li>
        <li>Business and website analysis and improvement;</li>
        <li>The provision of social features as part of our services;</li>
        <li>Customising your personal experience;</li>
        <li>
          To send you related information such as updates, security alerts and support messages;
        </li>
        <li>
          On-site and in-app advertising and promotion of our goods and services and those of our
          service providers and trusted third parties;
        </li>
        <li>Website, system administration and account verification;</li>
        <li>
          Leader boards, Discord and community information, nicknames and club name/club
          information;
        </li>
        <li>To moderate communications between players either automatically or manually;</li>
        <li>To answer or satisfy legal or regulatory requirements;</li>
        <li>
          When you interact with third party social networking features to serve you with
          advertisements and engage with you on third party social networks (we encourage you to
          review the privacy notices/policies of these social networks to enable you to opt out of
          such activities).
        </li>
      </ul>
    </section>

    <section>
      <p><em>4.Legal basis for processing</em></p>
      <p>
        There are a number of different legal grounds for processing personal information. Which one
        is applicable will depend on how we are using your information and for what purpose. In the
        majority of cases this condition will be that:
      </p>
      <ul>
        <li>
          You have provided your consent to us using your personal information in that way (for
          example where you provide us with consent to send you marketing communications about our
          products and services);
        </li>
        <li>
          Our use of your personal information is in our legitimate interest as a commercial
          organisation. For example, we currently are not but may at some point in the future use
          cookies to track information about how our website is used in order to continually improve
          its layout based on how you and other users interact with its content, and to personalise
          it to the user (for example, by showing content or a language which is relevant to your
          geographic location), provided it is conducted at all times in a way that is
          proportionate, and that respects your privacy rights;
        </li>
        <li>
          Our use of your personal information is necessary to perform a contract or take steps to
          enter into a contract with you (e.g. to manage your account);
        </li>
        <li>
          Our use of your personal information is necessary to comply with a relevant legal or
          regulatory obligation. We generally do not collect or process any 'special categories' of
          personal data (including information regarding your health, religious or political
          beliefs, ethnic background, sexual life and sexual orientation). If this would apply, we
          will generally rely on obtaining additional specific consent from you at the time we
          collect the information unless there is a legal requirement or other justification for
          processing that information.
        </li>
      </ul>
    </section>

    <section>
      <p><em>Children</em></p>
      <p>
        <em
          >You must be over a certain age to play our games and use our Services, depending on where
          you live. For the full list of age restrictions by country, please see below. We do not
          knowingly collect or solicit personal information from or direct or target interest based
          advertising to anyone under the ages set out below, or knowingly allow such persons to use
          our Services. If you believe that we might have any information from or about a child
          under the age set out below, please Contact Us.</em
        >
      </p>
      <p>
        The table below sets out what age you must be to play our games and use our Services,
        depending on what country you are in while using our games and Services. Our games are
        intended to be played by adults and we do not knowingly collect, and do not wish to collect,
        information about children. Please do not play our games or use our Services if you are
        under the relevant age.
      </p>

      <table>
        <thead>
          <tr>
            <td>Country</td>
            <td>Age</td>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>Austria</td>
            <td>14</td>
          </tr>
          <tr>
            <td>Belgium</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Bulgaria</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Croatia</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Republic of Cyprus</td>
            <td>14</td>
          </tr>
          <tr>
            <td>Czech Republic</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Denmark</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Estonia</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Finland</td>
            <td>13</td>
          </tr>
          <tr>
            <td>France</td>
            <td>15</td>
          </tr>
          <tr>
            <td>Germany</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Greece</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Hungary</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Ireland</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Italy</td>
            <td>14</td>
          </tr>
          <tr>
            <td>Latvia</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Lithuania</td>
            <td>14</td>
          </tr>
          <tr>
            <td>Luxembourg</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Malta</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Netherlands</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Norway</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Poland</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Portugal</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Romania</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Slovakia</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Slovenia</td>
            <td>16</td>
          </tr>
          <tr>
            <td>Spain</td>
            <td>14</td>
          </tr>
          <tr>
            <td>Sweden</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Switzerland</td>
            <td>16</td>
          </tr>
          <tr>
            <td>United Kingdom</td>
            <td>13</td>
          </tr>
          <tr>
            <td>Rest of the world (excluding South Korea)</td>
            <td>13</td>
          </tr>
        </tbody>
      </table>
      <p>
        If you believe that we might have any information from or about a child under the relevant
        age set out above, please Contact Us. In the event that we learn that we have collected
        personal information from a child under the relevant age set out above, we will delete that
        information as quickly as possible.
      </p>
    </section>

    <section>
      <p><em>6.Sharing your information</em></p>
      <p>
        The personal information you provide to us may be shared with third party companies, agents,
        contractors, service providers or our affiliated companies if this is necessary to provide
        you with our services, respond to your inquiries or for any of the purposes described in
        this policy. This may include:
      </p>
      <ul>
        <li>Our business partners and suppliers;</li>
        <li>
          Sub-processors who store or process information on our behalf, in particulardataanalytics
          providers and data storage providers. Information shared with such providers is supplied
          in an anonymised format such that, that data cannot be linked to any particular individual
          and is therefore not considered to be 'personal data';
        </li>
        <li>Our auditors, insurers, lawyers and other professional advisers;</li>
        <li>Credit reference agencies;</li>
        <li>
          Law enforcement agencies, other governmental agencies or third parties if we are required
          by law to do so;
        </li>
        <li>
          Other business entities should we plan to merge with or be acquired by that business
          entity, or if we undergo a re-organisation with that entity.
        </li>
      </ul>
    </section>

    <section>
      <p><em>7.Social Features</em></p>
      <p>
        Social features are a core component of our games. Other players and users may, for example,
        see your profile data, in-game activities and read the messages you have posted.
      </p>
      <p>
        Our games and services may include features from our partners, if any, such as social media
        interaction tools (and albeit not currently, in the future may also relate to in-game
        advertising). These partners, if any, may in such case, following your consent, access your
        data and operate under their own privacy policies. We encourage you to check their privacy
        policies to learn more about their data processing practices and opt out where you deem
        relevant.
      </p>
    </section>

    <section>
      <p><em>8.International Data Transfers</em></p>
      <p>
        Our Service is global by nature and your data can therefore be transferred to anywhere in
        the world. Because different countries may have different data protection laws than your own
        country, we take steps to ensure adequate safeguards are in place to protect your data as
        explained in this policy. Our relevant group entities and partners will use adequate
        safeguards, which may amongst others include EU-approved standard contractual clauses .
      </p>
    </section>

    <section>
      <p><em>9.Your rights</em></p>
      <p>
        Under EU data protection laws you have a number of rights in relation to your personal data.
        We respect and honour these rights and will help you to exercise them insofar as we are
        able. You have the right:
      </p>

      <ul>
        <li>To request access to or a copy of any personal data which we hold about you;</li>
        <li>
          To rectification of your personal data, if you consider that the information we are
          holding is inaccurate;
        </li>
        <li>
          To ask us to delete your personal data, if you consider that we do not have the right to
          hold it;
        </li>
        <li>
          To withdraw consent to our processing of your personal data (to the extent such processing
          is based on previously obtained consent);
        </li>
        <li>
          To ask us to stop or start sending you marketing messages as described below in the
          marketing section;
        </li>
        <li>To restrict processing of your personal data;</li>
        <li>
          To data portability (moving some of your personal data elsewhere) in certain
          circumstances;
        </li>
        <li>To object to your personal data being processed in certain circumstances;</li>
        <li>
          To not be subject to a decision based on automated processing and to have safeguards put
          in place if you are being profiled based on your personal data.
        </li>
      </ul>

      <p>
        Please note that these rights are not absolute – in some cases they will not apply to you,
        or to the particular use that we are making of your data, and there are exceptions (for
        example if we have to process the data to comply with our own legal obligations) but if that
        is the case we will let you know if you make a request that we believe we cannot comply
        with.
      </p>

      <p>
        Any request from you for access to or a copy of your personal data must be in writing and we
        will endeavour to respond within a reasonable period and in any event within one month in
        compliance with data protection legislation. We will comply with our legal obligations as
        regards your rights as a data subject.
      </p>

      <p>
        We aim to ensure that the information we hold about you is accurate at all times. To assist
        us in ensuring that your information is up to date, you have the option to fully control the
        data you shared with us, and you may update your information directly under your profile or
        adjust the settings on your device.
      </p>

      <p>
        You have a right to have some of the personal information that we hold about you deleted.
        Should you wish to have any information about you deleted, please Contact Us using the
        information below. Please note that in order to process your request you must delete our
        games from your mobile devices and clear our cookies from any device where you have played
        our games in a web browser. Where we delete personal information about you, we may still
        retain some or all of that information for other purposes such as maintaining financial
        records, protecting or enforcing legal rights, maintaining marketing suppression lists or
        for technical reasons such as maintaining technical security or our database integrity. We
        may also retain your information in an anonymised form. In some instances, personal
        information about you that is visible through gameplay such as username, avatar, your high
        scores and any chat messages may be cached on other players’ devices and we may not be able
        to remove or update that data from those devices, for example if that device is not
        connected to a wifi network.
      </p>

      <p>If you have an unresolved privacy or data use concern please contactus <EmailLink /></p>
    </section>

    <section>
      <p><em>10.Marketing</em></p>
      <p>
        If you have accepted to receive notifications for a certain game, we may use your personal
        information to send you tailored suggestions, offers or auction information about the game.
        For personalised in-game offers opt-out, you can use the options provided in the game
        settings. You can easily turn off the notification in each different category within the
        game or opt out from receiving notifications or alerts on your device.
      </p>
      <p>
        You can opt-out of interest-based advertising on mobile applications, if any, by checking
        the privacy settings of your Android or iOS device and selecting "limit ad tracking" (Apple
        iOS) or "opt-out of interest based ads" (Android).
      </p>
    </section>

    <section>
      <p><em>11.How long will we keep your information?</em></p>
      <p>
        We will only keep the information we collect about you for as long as required for the
        purposes set out in this notice or as required to comply with any legal obligations to which
        we are subject. This will involve us periodically reviewing our files to check that
        information is accurate, up-to-date and still required.
      </p>
      <p>
        By law we have to keep basic information about our customers (including contact, identity
        data, (and financial and transaction data relating to transactions via our store, if any))
        for six tax years plus the current tax year after they cease being customers for tax
        purposes.
      </p>
      <p>
        In some circumstances you can ask us to delete your data: see "Your rights" for further
        information.
      </p>
      <p>
        We may anonymise your personal data (so that it can no longer be associated with you) for
        research or statistical purposes in which case we may use this information indefinitely
        without further notice to you.
      </p>
      <p>
        If you opt out from marketing, we may retain the necessary information to enable us to
        respect your wishes to not be contacted for marketing purposes.
      </p>
    </section>

    <section>
      <p><em>12.Security</em></p>
      <p>
        We are committed to ensuring that your information is secure. In order to prevent
        unauthorised access or disclosure, we have put in place suitable physical, electronic and
        managerial procedures to safeguard and secure the information we collect. Such measures will
        be appropriate to the nature of the data concerned and the level of risk. If you have been
        provided with a password to access any of our services you should not share that password
        with anyone else.
      </p>
    </section>

    <section>
      <p><em>13.Links to Other Sites</em></p>
      <p>
        Our websites may contain links to other sites, including via our social media buttons. While
        we try to link only to websites that share our high standards and respect for privacy, we
        are not responsible for the content, security, or privacy practices employed by other
        websites and a link does not constitute an endorsement of that website. Once you link to
        another website from our website you are subject to the terms and conditions of that
        website, including, but not limited to, its internet privacy policy and practices. Please
        check these policies before you submit any data to these websites.
      </p>
    </section>

    <section>
      <p><em>14.Contact</em></p>
      <p>
        Questions, comments and requests regarding this policy are welcomed and should be addressed
        to <EmailLink />.
      </p>
    </section>

    <section>
      <p><em>15.Changes to this policy</em></p>
      <p>
        Any changes we make to our policy in the future will be posted on this page and, where
        material and appropriate, notified to you by in-game message. We urge you to check regularly
        to see any updates or changes to our policy.
      </p>
    </section>
  </div>
</template>

<style lang="scss" scoped>
@import '@/assets/document.scss';
</style>
